Repository wecode-bootcamp-korea/27-2nd-Hines-frontend, pull requests merged in 2021-12, with the labels that each got.

#2 [27기 황주영] mixin, 폰트 추가 및 수정
  package-lock.json
  package.json
  src/index.js
  src/pages/fonts/fonts/NotoSansKR-Bold.woff
  src/pages/fonts/fonts/NotoSansKR-Light.woff
  src/pages/fonts/fonts/NotoSansKR-Medium.woff
  src/pages/fonts/fonts/NotoSansKR-Regular.woff
  src/pages/fonts/fonts/fonts.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#4 [27기 홍정빈] Add: nav - 레이아웃 구현
  public/data/navTest.json
  public/images/symbolbk.png
  public/images/symbolwhite.png
  src/components/Nav/Nav.js
  src/components/Nav/NavModal.js
  src/components/Nav/SecondNav.js
  src/fonts/NotoSansKR-Bold.woff
  src/fonts/NotoSansKR-Light.woff
  src/fonts/NotoSansKR-Medium.woff
  src/fonts/NotoSansKR-Regular.woff
  src/fonts/fonts.js
  src/hooks/useNavModal.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#3 [27기 이지현] Modify : 콘솔로그 제거
  public/images/kakao_login_medium_wide.png
  public/images/space_background.jpg
  public/index.html
  src/pages/Login/Login.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#7 [27기 이지현] Modify : 상세페이지 통신에 맞게 재구성
  package-lock.json
  public/data/detailData.json
  public/images/naverlog.png
  public/images/sample.png
  src/Router.js
  src/pages/ProductDetail/ProductDetail.js
  src/styles/theme.js
Labels: Status: 추가 기능 구현중, Status: 수정 요청

#5 [27기 홍정빈] Add: cart 레이아웃 완성
  public/data/cartTest.json
  src/pages/Cart/Cart.js
  src/pages/Cart/OrderBox.js
  src/pages/Cart/ProductBox.js
Labels: Status: Rebase 요청

#9 [27기 황주영] Add: 주문확인페이지 레이아웃 get 기능 구현
  public/data/orderinfodata.json
  src/Router.js
  src/config.js
  src/pages/Orderlist/OrderClientInfo.js
  src/pages/Orderlist/OrderInfo.js
  src/pages/Orderlist/Orderlist.js
Labels: Status: 리뷰 요청

#1 [27기 황주영] Add: 메인페이지 쿼리파라미터 구현
  public/bannerimage/maintop.png
  public/data/ProductListData.json
  public/data/categoryData.json
  public/data/subCategoryData.json
  public/samplesize.png
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/NavModal.js
  src/components/Nav/SecondNav.js
  src/components/Nav/categoryData.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/ProductList/CategoryAside/CategoryAsie.js
  src/pages/ProductList/Product/MostCardData.js
  src/pages/ProductList/Product/MostProductCard.js
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductListBanner.js
  src/styles/GlobalStyle.js
Labels: Status: 수정 요청, Status: 리뷰 요청

#12 [27기 이지현] Modify : 카카오 자동 로그인 완성
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#11 [27기 황주영] modify : config 수정, 각페이지 API 재설정
  src/config.js
  src/pages/Login/Login.js
  src/pages/Orderlist/Orderlist.js
  src/pages/ProductDetail/.ProductDetail.js.swp
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/Product/Product.js
Labels: Status: Accepted

#13 [27기 이지현] Modify : 주문하기 추가, 리뷰 페이지네이션 버튼만 추가
  public/data/reviewData.json
  src/config.js
  src/pages/ProductDetail/ProductDetail.js
Labels: Status: 리뷰 요청

#14 [27기 홍정빈] Add: cart 기능 추가 및 병합을 위한 PR 요청
  public/data/cartTest.json
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/OrderBox.js
  src/pages/Cart/ProductBox.js
Labels: Status: 리뷰 요청

#15 [27기 황주영] modify:불필요한 태그 삭제
  src/config.js
  src/pages/Orderlist/Orderlist.js
  src/pages/ProductList/CategoryAside/CategoryAsie.js
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#16 [27기 이지현] ADD : 리뷰 페이지네이션 기능 완료
  public/data/reviewData.json
  src/components/ReviewPageMoveBtnList.js
  src/pages/ProductDetail/ProductDetail.js
Labels: Status: 리뷰 요청

#17 [27기 홍정빈] Fix: fatch 통신 수정
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/OrderBox.js
  src/pages/Cart/ProductBox.js
Labels: Status: 리뷰 요청

#18 [27기 황주영] 페이지별 토큰 분기처리
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/ProductDetail/ProductDetail.js
Labels: Status: 리뷰 요청
